
CREATE TABLE PM_BASE_RIGHT
(
  BASE_RIGHT_ID      NUMBER                     NOT NULL,
  BASE_RIGHT_NAME    NVARCHAR2(2000)            NOT NULL,
  RIGHT_ID           NUMBER                     NOT NULL,
  PRIORITY           NUMBER                     NOT NULL,
  DEFAUT_ALLOW_DENY  NUMBER(1)                  NOT NULL
);


CREATE UNIQUE INDEX PM_BASE_RIGHT_UK1 ON PM_BASE_RIGHT (RIGHT_ID, BASE_RIGHT_NAME);
CREATE UNIQUE INDEX PM_BASE_RIGHT_PK ON PM_BASE_RIGHT(BASE_RIGHT_ID);
ALTER TABLE PM_BASE_RIGHT ADD (CONSTRAINT PM_BASE_RIGHT_PK PRIMARY KEY (BASE_RIGHT_ID));
ALTER TABLE PM_BASE_RIGHT ADD (CONSTRAINT PM_BASE_RIGHT_UK1 UNIQUE (RIGHT_ID, BASE_RIGHT_NAME));
ALTER TABLE PM_BASE_RIGHT ADD (CONSTRAINT PM_BASE_RIGHT_PM_RIGHT_GR_FK1 FOREIGN KEY (RIGHT_ID) REFERENCES PM_RIGHT_GROUP (RIGHT_ID) ON DELETE CASCADE);

=======================================================



CREATE TABLE PM_PERMISSION_MASTER
(
  RESOURCE_ID           NUMBER                  NOT NULL,
  RESOURCE_TYPE_ID      NUMBER                  NOT NULL,
  ENTITY_ID             NUMBER                  NOT NULL,
  ENTITY_TYPE_ID        NUMBER                  NOT NULL,
  BASE_RIGHT_ID         NUMBER,
  IS_ALLOWED            INTEGER,
  IS_INHERITED          INTEGER,
  PERMISSION_MASTER_PK  NUMBER                  NOT NULL
);


CREATE UNIQUE INDEX PM_PERMISSION_MASTER_PK1 ON PM_PERMISSION_MASTER(PERMISSION_MASTER_PK);
CREATE UNIQUE INDEX PM_PERMISSION_MASTER_UK1 ON PM_PERMISSION_MASTER(RESOURCE_ID, RESOURCE_TYPE_ID, ENTITY_ID, ENTITY_TYPE_ID, BASE_RIGHT_ID);
ALTER TABLE PM_PERMISSION_MASTER ADD (CONSTRAINT PM_PERMISSION_MASTER_PK1 PRIMARY KEY (PERMISSION_MASTER_PK));
ALTER TABLE PM_PERMISSION_MASTER ADD (CONSTRAINT PM_PERMISSION_MASTER_UK1 UNIQUE (RESOURCE_ID, RESOURCE_TYPE_ID, ENTITY_ID, ENTITY_TYPE_ID, BASE_RIGHT_ID));
ALTER TABLE PM_PERMISSION_MASTER ADD (CONSTRAINT PM_PERMISSION_MASTER_PM_B_FK1 FOREIGN KEY (BASE_RIGHT_ID) REFERENCES PM_BASE_RIGHT (BASE_RIGHT_ID) ON DELETE CASCADE);

=============================================================


CREATE TABLE PM_RIGHTS_RESOURCE_RELATION
(
  RESOURCE_ID       NUMBER                      NOT NULL,
  RESOURCE_TYPE_ID  NUMBER                      NOT NULL,
  RIGHT_GROUP_ID    NUMBER                      NOT NULL,
  RELATION_PK       NUMBER                      NOT NULL
);


CREATE UNIQUE INDEX PM_RIGHTS_RESOURCE_RELATI_UK1 ON PM_RIGHTS_RESOURCE_RELATION(RESOURCE_ID, RESOURCE_TYPE_ID, RIGHT_GROUP_ID);
CREATE UNIQUE INDEX PM_RIGHTS_RESOURCE_RELATI_PK ON PM_RIGHTS_RESOURCE_RELATION(RELATION_PK);
ALTER TABLE PM_RIGHTS_RESOURCE_RELATION ADD (CONSTRAINT PM_RIGHTS_RESOURCE_RELATI_PK PRIMARY KEY (RELATION_PK));
ALTER TABLE PM_RIGHTS_RESOURCE_RELATION ADD (CONSTRAINT PM_RIGHTS_RESOURCE_RELATI_UK1 UNIQUE (RESOURCE_ID, RESOURCE_TYPE_ID, RIGHT_GROUP_ID));
ALTER TABLE PM_RIGHTS_RESOURCE_RELATION ADD (CONSTRAINT PM_RIGHTS_RESOURCE_RELATI_FK1 FOREIGN KEY (RIGHT_GROUP_ID) REFERENCES PM_RIGHT_GROUP (RIGHT_ID) ON DELETE CASCADE);

===================================================



CREATE TABLE PM_RIGHT_GROUP
(
  RIGHT_ID    NUMBER                            NOT NULL,
  RIGHT_NAME  NVARCHAR2(2000)                   NOT NULL
);


CREATE UNIQUE INDEX PM_RIGHT_GROUP_UK1 ON PM_RIGHT_GROUP(RIGHT_NAME);
CREATE UNIQUE INDEX PM_RIGHT_GROUP_PK ON PM_RIGHT_GROUP(RIGHT_ID);
ALTER TABLE PM_RIGHT_GROUP ADD (CONSTRAINT PM_RIGHT_GROUP_PK PRIMARY KEY (RIGHT_ID));
ALTER TABLE PM_RIGHT_GROUP ADD (CONSTRAINT PM_RIGHT_GROUP_UK1 UNIQUE (RIGHT_NAME));